### ISSUE TITLE
Support for Italian language

### ISSUE THREAD

**Issue by llegovich** [openhab/org.openhab.ui.habot#42]
Would like for the Italian language. I'm italian, how can I contribute? Thx

**Comment by ghys** [comment]
Hi, it's a somewhat involved process. You'll have to:

1. Provide translations in Italian to the semantic tags here:
https://github.com/openhab/openhab-core/tree/master/bundles/org.openhab.core.semantics/src/main/resources
(that is, add a tags_it.properties file through a PR)

2. Provide training data (including tests) and translations for greetings & answers with a PR to this repository. Basically what was done for Dutch in #32.

**Comment by llegovich** [comment]
Hi, I'm sorry but I'm new to github and don't know the right way to create the pull request. I have the files translated, could you guide me in uploading them?
thanks.

**Comment by kubawolanin** [comment]
> I have the files translated, could you guide me in uploading them?

Check out these step-by-step tutorials:
https://help.github.com/articles/set-up-git/
https://help.github.com/articles/fork-a-repo/

**Comment by llegovich** [comment]
I have created the pull request. Please review and merfe. Thx.

**Comment by kaikreuzer** [comment]
That's awesome @llegovich, thanks!
I am just afraid that someone should have told you that the code has meanwhile moved to https://github.com/openhab/openhab-webui/tree/master/bundles/org.openhab.ui.habot (@ghys we should consider to add big notes on the readme of the old repos and maybe rename them, wdyt?).

@llegovich May I thus ask you to check out https://github.com/openhab/openhab-webui and create your PR against this? (should really be just a move of your files to that repo, I don't think it should be much effort, otherwise I would not dare to ask ;-)). Thanks!

**Comment by llegovich** [comment]
Hi @kaikreuzer I have created the pull request on the new repo. Hope it's ok.
thanks.
